### ISSUE TITLE
gestire le variabili

### ISSUE THREAD

**Issue by mauri1982** [mauri1982/ajax_prova#11]
per passare le variabili da una funzione all'altra se ho ben capito, non devo usare var.

es

function miaFunzione(){
  pippo=5;
secondaFunzione();
}

secondaFunzione(){
pippo++;
return pippo;
}

se mettessi var pippo, il valore non passerebbe, giusto?
ho provato anche ad inserire pippo come parametro, ma non viene passato (naturalmente deve essere parametrico anche nella seconda fun)

**Comment by karimone** [comment]
https://jsfiddle.net/gx6b3w8v/
