### ISSUE TITLE
revisione wanted

### ISSUE THREAD

**Issue by mauri1982** [mauri1982/ajax_prova#4]
fixato:
-codice max di 4 caratteri
-puls get it che si attiva solo con 4 cifre inserite
-warning di code inesistente
-aggiunta grafica (spartana)

richiesta revisione

**Comment by karimone** [comment]
Ho creato un nuovo branch con le mie modifiche che sono soltanto di separazione. Guardando il codice e provando c'e' qualche problema di usabilita' e di funzionalita'.

* I sobborghi restituiti non vengono mostrati tutti, ma solo il primo.
* Il bottone "Get" dovrebbe essere disabilitato anche visivamente.
* Se premo invio ed il postcode e' valido, deve fare la stessa cosa del bottone
* Se il postcode non e' valido la textinput deve essere rossa.

**Comment by mauri1982** [comment]
sistemato tutto
