### ISSUE TITLE
working on mozilla

### ISSUE THREAD

**Issue by mauri1982** [mauri1982/ajax_prova#6]
non sono riuscito a superare il problema del blocco datie devo lavorare con ie 2  ... :\

**Comment by karimone** [comment]
Che e' una merda, l'unico modo sarebbe lavorare con un proprio backend... a breve passiamo a Django :-)

**Comment by mauri1982** [comment]
porca madonna. per sistemare due mappe ci ho messo 8 ore. voglio vedere con django. in un mese sistemo un input box
